Add omicron levels coloring
nextstrain/ncov pull request #1018
Opened 2022-10-19 00:51 UTC by jameshadfield

For background please see "Variant report 2022-10-17" section of https://github.com/neherlab/SARS-CoV-2_variant-reports/blob/main/reports/variant_report_latest_draft.md for details of lineage classification. This commit is very much a first pass to see if (a) it works robustly on large datasets and (b) there is interest in including it (there is from me!)

Note that the mutations are relative to BA.2 so we should really use this for omicron-only builds, which are being developed elsewhere. This is especially relevant for S:493 where we consider a reversion to increase the level, meaning strains basal to BA.2 will be elevated inappropriately.

I'll kick off trial builds now...

cc @corneliusroemer

2022-10-19 11:23 UTC, corneliusroemer requested changes
Really good

The level definitions are somewhat arbitrary at the boundaries - they are informed by what we commonly see - could be subject to change.

2022-10-19 11:23 UTC, corneliusroemer commented on scripts/assign_levels.py
> +    ("V", 445, ("P")),
```suggestion
    ("V", 445, ("A","P")),
```

2022-10-19 11:23 UTC, corneliusroemer commented on scripts/assign_levels.py
> +    ("K", 444, ("T", "R")),
```suggestion
    ("K", 444, ("T", "R","N","M")),
```

2022-10-19 11:23 UTC, corneliusroemer commented on scripts/assign_levels.py
> +    ("G", 446, ("S")),
```suggestion
    ("G", 446, ("S","D")),
```

2022-10-19 11:23 UTC, corneliusroemer commented on scripts/assign_levels.py
> +    ("L", 452, ("R")),
```suggestion
    ("L", 452, ("R","Q","M")),
```

2022-10-19 11:23 UTC, corneliusroemer commented on scripts/assign_levels.py
> +    ("F", 490, ("S")),
```suggestion
    ("F", 490, ("S","V","L","P")),
```

2022-10-19 11:24 UTC, corneliusroemer commented
Excellent stuff @jameshadfield.

1. It'd be great if we could make non-21L and descendants grey, as opposed to 0
2. Maybe call it `RBD level 7` etc.

It's great, definitely _already_ useful as is, could just merge and improve over time. Maybe greying out non-21L descendants is the only important change.

2022-10-19 21:37 UTC, jameshadfield commented
Thanks @corneliusroemer. I'll move the definitions out of a script into a config (easy), change the name to `RBD level X` (easy) and see if I can make non-21L genomes grey (should be easy?). Watch this space...

2022-10-19 22:45 UTC, jameshadfield commented
Applied @corneliusroemer's changes to the definitions and generally made this PR into something that is maintainable going forward. Changes to the level definitions are made by modifying `defaults/rbd_levels.yaml` rather than the script itself. 

But I see that CI has failed because "ERROR: no node found with a clade_annotation of 21L (Omicron)". We want to allow this to work on all trees, even if they don't have any omicron sequences, so I'll update this now.

2022-10-19 22:57 UTC, jameshadfield commented
Test builds (GenBank this time) running now. I'll merge this as long as it completes succsessfully:

--> Trial name is: feat-levels-mk2

--> When completed, the following will be available:
build files: s3://nextstrain-staging/files/ncov/open/trial/feat-levels-mk2/
nextstrain URLs: https://nextstrain.org/staging/ncov/open/trial/feat-levels-mk2/REGION_NAME

--> You can attach to this AWS job via:
nextstrain build --aws-batch --attach 4ef45461-1577-4d7c-ae7b-6c4373b37a0d /home/runner/work/ncov/ncov

--> View this job in the AWS console via
    https://console.aws.amazon.com/batch/home?region=us-east-1#jobs/detail/4ef45461-1577-4d7c-ae7b-6c4373b37a0d

2022-10-20 02:36 UTC, jameshadfield commented
That trial build failed, here's another one...

--> Trial name is: feat-levels-mk3

--> When completed, the following will be available:
build files: s3://nextstrain-staging/files/ncov/open/trial/feat-levels-mk3/
nextstrain URLs: https://nextstrain.org/staging/ncov/open/trial/feat-levels-mk3/REGION_NAME

--> You can attach to this AWS job via:
nextstrain build --aws-batch --attach 9ec158cd-dda8-4e42-b6dd-89b8327f93f4 /home/runner/work/ncov/ncov

--> View this job in the AWS console via
    https://console.aws.amazon.com/batch/home?region=us-east-1#jobs/detail/9ec158cd-dda8-4e42-b6dd-89b8327f93f4

2022-10-20 20:08 UTC, jameshadfield commented
[Trial build looks good](https://next.nextstrain.org/staging/ncov/open/trial/feat-levels-mk3/global/2m?c=rbd_level)

![image](https://user-images.githubusercontent.com/8350992/197047678-9e1c980a-64d8-4173-9be2-47c668992862.png)

2022-10-20 20:46 UTC, jameshadfield commented
[the following discussion from slack]
* I've changed the title from `RBD levels` to `RBD Levels`
* The frequencies panel is not colored appropriately due to an ordinal scale. This is a simple fix on Auspice's side (https://github.com/nextstrain/auspice/issues/843) which I'll get to ASAP

2022-10-20 20:50 UTC, merged