Add "1m" timespan in Nextstrain profiles
nextstrain/ncov pull request #1027
Opened 2022-11-02 18:27 UTC by victorlin

## Description of proposed changes

Motivated by [this Slack thread](https://bedfordlab.slack.com/archives/CSKMU6YUC/p1665755551606909).

Will post preview links when they are ready.

## Related issue(s)

_N/A_

## Testing

- [x] Start trial runs
    - [GISAID](https://github.com/nextstrain/ncov/actions/runs/3380122623)
    - [open](https://github.com/nextstrain/ncov/actions/runs/3380123888)

## Release checklist

If this pull request introduces backward incompatible changes, complete the following steps for a new release of the workflow:

 - [ ] Determine the version number for the new release by incrementing [the most recent release](https://github.com/nextstrain/ncov/releases) (e.g., "v2" from "v1").
 - [ ] Update `docs/src/reference/change_log.md` in this pull request to document these changes and the new version number.
 - [ ] After merging, [create a new GitHub release](https://github.com/nextstrain/ncov/releases/new) with the new version number as the tag and release title.

If this pull request introduces new features, complete the following steps:

 - [ ] Update `docs/src/reference/change_log.md` in this pull request to document these changes by the date they were added.

2022-11-03 00:07 UTC, corneliusroemer commented
Here are the job ids so one can check logs, open should be done by now but isn't...

```
nextstrain build --aws-batch --no-download --attach a3447a21-283d-4439-aef0-4f837dbcc89e .
nextstrain build --aws-batch --no-download --attach e64c991b-5d71-4eab-853a-9f1b757f1cf5 .
```

2022-11-03 00:17 UTC, corneliusroemer requested changes
Both trial runs unfortunately failed, see comment

2022-11-03 00:20 UTC, victorlin commented
Thanks for digging into that @corneliusroemer. I'm about to sign out for the day, so feel free to make changes on the PR branch to your desire. Otherwise I can pick up on it tomorrow.

2022-11-03 17:29 UTC, victorlin commented
As @trvrb [mentioned in Slack](https://bedfordlab.slack.com/archives/CSKMU6YUC/p1667434685478259?thread_ts=1665755551.606909&cid=CSKMU6YUC), logistic growth is [set to 6 weekly pivots](https://github.com/nextstrain/ncov/blob/c220e1d7d228819a0b1f6c42ba5f27106003b9b6/defaults/parameters.yaml#L161) which is too much when frequencies is limited by `--min-date 1M`. I've pushed c220e1d7d228819a0b1f6c42ba5f27106003b9b6 which should fix this. Will run new trial builds.

2022-11-03 17:32 UTC, victorlin commented
Also @corneliusroemer it's the same error for both GISAID and open.

2022-11-03 23:49 UTC, corneliusroemer commented
Excellent, now it works. I think we can make the bucket size bigger to get more recent sequences for the open build. We only have 1.3k sequences from last 1M and 2k sequences in total.

A build with 4k sequences is a good size, so we can add another 2k sequences from the most recent month to make it as useful as possible.

2022-11-03 23:58 UTC, victorlin commented
@corneliusroemer I've just rebased onto latest master so it has your changes to upload builds as they are done. I think it'd be best if you take over this branch now and tweak to your desire. Would you be willing to do that?

2022-11-08 22:57 UTC, corneliusroemer commented on docs/src/reference/change_log.md
> +- X November 2022: Add "2m" timespan in Nextstrain profile builds. [PR 1027](https://github.com/nextstrain/ncov/pull/1027)
```suggestion
- 8 November 2022: Add "1m" timespan in Nextstrain profile builds. [PR 1027](https://github.com/nextstrain/ncov/pull/1027)

```

2022-11-08 22:57 UTC, corneliusroemer commented on docs/src/reference/change_log.md
> +- X November 2022: calculate_delta_frequency: Allow script to work with fewer pivots available than requested with `--delta-pivots`. [PR 1027](https://github.com/nextstrain/ncov/pull/1027)
```suggestion
- 8 November 2022: calculate_delta_frequency: Allow script to work with fewer pivots available than requested with `--delta-pivots`. [PR 1027](https://github.com/nextstrain/ncov/pull/1027)

```

2022-11-08 22:58 UTC, corneliusroemer approved these changes

2022-11-11 16:48 UTC, rneher approved these changes

2022-11-24 14:41 UTC, merged

2022-12-28 21:20 UTC, victorlin commented
@corneliusroemer FYI, I'm deleting your branch `very-recent-1m` at ca23d68ef2abf1b5b7eb5b2551b135840f39a627 (it looks like an old test branch related to this PR).