Fix nnz scipy issue with proximity_score job
nextstrain/ncov pull request #545
Opened 2021-02-02 21:59 UTC by ericenns

### Description of proposed changes    
Fixes Issue with running proximity_score job on latest pull from GISAID of ~425000 sequences. Fix was identified from issue on scipy repo https://github.com/scipy/scipy/issues/12495

### Related issue(s)  

Fixes #512 

### Testing
What steps should be taken to test the changes you've proposed?  
If you added or changed behavior in the codebase, did you update the tests, or do you need help with this?  

### Thank you for contributing to Nextstrain!

2021-02-03 08:23 UTC, michalkowalski94 requested changes
There are incompatibilities between python3.7 and packages from pip.
With python 3.6 this fix is producing conflicts within conda.
Also scipy=1.6.0 is not available within defaults or bioconda, so adding conda-forge to channels is crucial.

UPDATE:
It actually works with
`python=3.7.1`
and scipy is installed automatically within pip packages enlisted at the bottom of yaml

2021-02-03 14:50 UTC, ericenns commented
Hi @michalkowalski94 your right that just changing the python version to 3.7.* does ensure that scipy 1.6.0 is installed through the pip dependencies. I will remove the scipy conda package then.

I don't need to install snakemake for the conda env as I am running the pipeline with `--use-conda` argument. It also looks like someone else has a PR to add snakemake to the env,

2021-02-13 14:33 UTC, rneher commented
@huddlej We have run into this issue as well and upgrading scipy fixed it. I'll let you review this.

2021-02-18 22:56 UTC, huddlej approved these changes
This works for me, although I haven't run into the specific scipy issue that this issue is supposed to resolve, so I can't confirm that this change fixes that issue. I can confirm that this environment installs scipy 1.6.1 for me, which should be good enough.

As a side note for the Nextstrain team, scipy only gets installed in the ncov workflow because it is a dependency of `phylo-treetime` (which is a dependency of `augur`). If we really want to pin a minimum scipy version for this workflow in the future, we should add scipy to our pip dependencies like so (to get a pre-built wheel from PyPI instead of a potentially out-of-date conda package):

```
name: nextstrain
channels:
- bioconda
- defaults
dependencies:
- cvxopt
- datrie
- fasttree
- iqtree
- mafft=7.471
- pandas
- psutil
- python=3.7*
- nodejs=10
- raxml
- vcftools
- git
- pip
- pip:
  - awscli==1.18.45
  - nextstrain-augur==10.3.0
  - nextstrain-cli==1.16.5
  - rethinkdb==2.3.0.post6
  - scipy==1.6.1
```

2021-02-18 22:56 UTC, merged